apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: iad-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: location
            operator: In
            values: [ 'us' ]
---
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: iad
  namespace: fleet-default
  labels:
    environment: virtual
    edge-arch: single-node
    region: dc
    airport: iad
    geo: dc
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: iad-machine-selector
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
  kubernetesVersion: v1.23.7+k3s1
